/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable @typescript-eslint/no-empty-interface */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestOptions,
} from '@elastic/transport'
import * as T from './types'
interface That { transport: Transport }

export default class API {
  async getHealth (this: That, params?: T.GetHealthRequest, options?: TransportRequestOptions): Promise<T.GetHealthResponse> {
    return await this.transport.request<T.GetHealthResponse>({
      method: 'GET',
      path: `/api/ent/v1/internal/health`,
    }, options)
  }

  async getReadOnly (this: That, params?: T.GetReadOnlyRequest, options?: TransportRequestOptions): Promise<T.GetReadOnlyResponse> {
    return await this.transport.request<T.GetReadOnlyResponse>({
      method: 'GET',
      path: `/api/ent/v1/internal/read_only_mode`,
    }, options)
  }

  async putReadOnly (this: That, params: T.PutReadOnlyRequest, options?: TransportRequestOptions): Promise<T.PutReadOnlyResponse> {
    const {
      body,
      ...querystring
    } = params ?? {}
    return await this.transport.request<T.PutReadOnlyResponse>({
      method: 'PUT',
      path: `/api/ent/v1/internal/read_only_mode`,
      querystring,
      body: body
    }, options)
  }

  async getStats (this: That, params?: T.GetStatsRequest, options?: TransportRequestOptions): Promise<T.GetStatsResponse> {
    const {
      ...querystring
    } = params ?? {}
    return await this.transport.request<T.GetStatsResponse>({
      method: 'GET',
      path: `/api/ent/v1/internal/stats`,
      querystring
    }, options)
  }

  async getStorage (this: That, params?: T.GetStorageRequest, options?: TransportRequestOptions): Promise<T.GetStorageResponse> {
    return await this.transport.request<T.GetStorageResponse>({
      method: 'GET',
      path: `/api/ent/v1/internal/storage`,
    }, options)
  }

  async getStaleStorage (this: That, params?: T.GetStaleStorageRequest, options?: TransportRequestOptions): Promise<T.GetStaleStorageResponse> {
    return await this.transport.request<T.GetStaleStorageResponse>({
      method: 'GET',
      path: `/api/ent/v1/internal/storage/stale`,
    }, options)
  }

  async deleteStaleStorage (this: That, params?: T.DeleteStaleStorageRequest, options?: TransportRequestOptions): Promise<T.DeleteStaleStorageResponse> {
    const {
      ...querystring
    } = params ?? {}
    return await this.transport.request<T.DeleteStaleStorageResponse>({
      method: 'DELETE',
      path: `/api/ent/v1/internal/storage/stale`,
      querystring
    }, options)
  }

  async getVersion (this: That, params?: T.GetVersionRequest, options?: TransportRequestOptions): Promise<T.GetVersionResponse> {
    return await this.transport.request<T.GetVersionResponse>({
      method: 'GET',
      path: `/api/ent/v1/internal/version`,
    }, options)
  }
}
