/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface GetApiLogsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  /**
   * Filter date from
   */
  fromDate: string
  /**
   * Filter date to
   */
  toDate: string
  /**
   * The page to fetch. Defaults to 1
   */
  currentPage?: number
  /**
   * The number of results per page
   */
  pageSize?: number
  /**
   * Use this to specify a particular endpoint, like analytics, search, curations and so on
   */
  query?: string
  /**
   * Filter based on a particular status code: 400, 401, 403, 429, 200
   */
  httpStatusFilter?: string
  /**
   * Filter based on a particular HTTP method: GET, POST, PUT, PATCH, DELETE
   */
  httpMethodFilter?: string
  /**
   * Would you like to have your results ascending, oldest to newest, or descending, newest to oldest?
   */
  sort_direction?: string
}

export interface GetApiLogsResponse {}

/** The API Log displays API request and response data at the Engine level */
export async function getApiLogs (this: That, opts: GetApiLogsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<GetApiLogsResponse>
export async function getApiLogs (this: That, opts: GetApiLogsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<GetApiLogsResponse, unknown>>
export async function getApiLogs (this: That, opts: GetApiLogsOptions, transportOptions?: TransportRequestOptions): Promise<GetApiLogsResponse>
export async function getApiLogs (this: That, opts: GetApiLogsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'GET',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/logs/api`,
    querystring: {}
  }

  if (opts.fromDate !== undefined) (params.querystring as Record<string, any>).fromDate = opts.fromDate
  if (opts.toDate !== undefined) (params.querystring as Record<string, any>).toDate = opts.toDate
  if (opts.currentPage !== undefined) (params.querystring as Record<string, any>).currentPage = opts.currentPage
  if (opts.pageSize !== undefined) (params.querystring as Record<string, any>).pageSize = opts.pageSize
  if (opts.query !== undefined) (params.querystring as Record<string, any>).query = opts.query
  if (opts.httpStatusFilter !== undefined) (params.querystring as Record<string, any>).httpStatusFilter = opts.httpStatusFilter
  if (opts.httpMethodFilter !== undefined) (params.querystring as Record<string, any>).httpMethodFilter = opts.httpMethodFilter
  if (opts.sort_direction !== undefined) (params.querystring as Record<string, any>).sort_direction = opts.sort_direction

  return await this.transport.request<GetApiLogsResponse>(params, transportOptions)
}
