/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface DeleteMetaEngineSourceOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  sourceEngines: string[]
}

export interface DeleteMetaEngineSourceResponse {}

/** Delete a source engine from a meta engine */
export async function deleteMetaEngineSource (this: That, opts: DeleteMetaEngineSourceOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<DeleteMetaEngineSourceResponse>
export async function deleteMetaEngineSource (this: That, opts: DeleteMetaEngineSourceOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<DeleteMetaEngineSourceResponse, unknown>>
export async function deleteMetaEngineSource (this: That, opts: DeleteMetaEngineSourceOptions, transportOptions?: TransportRequestOptions): Promise<DeleteMetaEngineSourceResponse>
export async function deleteMetaEngineSource (this: That, opts: DeleteMetaEngineSourceOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'DELETE',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/source_engines`,
    querystring: {},
    body: {}
  }

  params.body = opts?.sourceEngines
  return await this.transport.request<DeleteMetaEngineSourceResponse>(params, transportOptions)
}

export interface AddMetaEngineSourceOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  sourceEngines: string[]
}

export interface AddMetaEngineSourceResponse {}

/** Add a source engine to an existing meta engine */
export async function addMetaEngineSource (this: That, opts: AddMetaEngineSourceOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<AddMetaEngineSourceResponse>
export async function addMetaEngineSource (this: That, opts: AddMetaEngineSourceOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<AddMetaEngineSourceResponse, unknown>>
export async function addMetaEngineSource (this: That, opts: AddMetaEngineSourceOptions, transportOptions?: TransportRequestOptions): Promise<AddMetaEngineSourceResponse>
export async function addMetaEngineSource (this: That, opts: AddMetaEngineSourceOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/source_engines`,
    querystring: {},
    body: {}
  }

  params.body = opts?.sourceEngines
  return await this.transport.request<AddMetaEngineSourceResponse>(params, transportOptions)
}
