/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface LogClickthroughOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  /**
   * Search query text
   */
  queryText: string
  /**
   * The ID of the document that was clicked on
   */
  document_id: string
  /**
   * The request ID returned in the meta tag of a search API response
   */
  request_id?: string
  /**
   * Array of strings representing additional information you wish to track with the clickthrough
   */
  tags?: string[]
}

export interface LogClickthroughResponse {}

/** Send data about clicked results */
export async function logClickthrough (this: That, opts: LogClickthroughOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<LogClickthroughResponse>
export async function logClickthrough (this: That, opts: LogClickthroughOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<LogClickthroughResponse, unknown>>
export async function logClickthrough (this: That, opts: LogClickthroughOptions, transportOptions?: TransportRequestOptions): Promise<LogClickthroughResponse>
export async function logClickthrough (this: That, opts: LogClickthroughOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/click`,
    querystring: {},
    body: {}
  }

  if (opts.queryText !== undefined) (params.querystring as Record<string, any>).queryText = opts.queryText
  if (opts.document_id !== undefined) (params.querystring as Record<string, any>).document_id = opts.document_id
  if (opts.request_id !== undefined) (params.querystring as Record<string, any>).request_id = opts.request_id
  if (opts.tags !== undefined) (params.querystring as Record<string, any>).tags = opts.tags

  return await this.transport.request<LogClickthroughResponse>(params, transportOptions)
}
