/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable import/export, @typescript-eslint/no-misused-new, @typescript-eslint/no-extraneous-class */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import { getHealth } from './_api_ent_v1_internal_health'
import { getReadOnly, putReadOnly } from './_api_ent_v1_internal_read_only_mode'
import { getStats } from './_api_ent_v1_internal_stats'
import { getVersion } from './_api_ent_v1_internal_version'

export default interface API {
  new(): API
  getHealth: typeof getHealth
  getReadOnly: typeof getReadOnly
  putReadOnly: typeof putReadOnly
  getStats: typeof getStats
  getVersion: typeof getVersion
}

export default class API {}
API.prototype.getHealth = getHealth
API.prototype.getReadOnly = getReadOnly
API.prototype.putReadOnly = putReadOnly
API.prototype.getStats = getStats
API.prototype.getVersion = getVersion
