---
steps:
  - label: ":js: :elastic-enterprise-search:"
    agents:
      provider: gcp
    matrix:
      setup:
        nodejs:
          - "18"
          - "20"
        stack_version:
          - "8.14.0-SNAPSHOT"
    env:
      NODE_JS_VERSION: "{{ matrix.nodejs }}"
      STACK_VERSION: "{{ matrix.stack_version }}"
    command: ./.buildkite/run-tests
    artifact_paths: "*-junit.xml"
