#!/usr/bin/env bash
#
# Version 1.1
# - Moved to .buildkite folder and separated out `run-repository.sh`
# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products
export TEST_SUITE=platinum
export CONTAINER_NAME=enterprise-search
export RUNSCRIPTS=enterprise-search

script_path="$(dirname "$(realpath -s "$0")")"
source "$script_path/functions/imports.sh"
set -euo pipefail

echo "--- :elasticsearch: starting Elasticsearch $STACK_VERSION"
DETACH=true bash .buildkite/run-elasticsearch.sh

if [[ -n "$RUNSCRIPTS" ]]; then
  for RUNSCRIPT in ${RUNSCRIPTS//,/ } ; do
    echo "--- Running run-$RUNSCRIPT.sh"
    CONTAINER_NAME=${RUNSCRIPT} \
      DETACH=true \
      bash ".buildkite/run-${RUNSCRIPT}.sh"
  done
fi

echo -e ":javascript: Run tests"
bash .buildkite/run-repository.sh
