/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface GetSearchSettingsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
}

export interface GetSearchSettingsResponse {}

/** Retrieve current search settings for the engine */
export async function getSearchSettings (this: That, opts: GetSearchSettingsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<GetSearchSettingsResponse>
export async function getSearchSettings (this: That, opts: GetSearchSettingsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<GetSearchSettingsResponse, unknown>>
export async function getSearchSettings (this: That, opts: GetSearchSettingsOptions, transportOptions?: TransportRequestOptions): Promise<GetSearchSettingsResponse>
export async function getSearchSettings (this: That, opts: GetSearchSettingsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'GET',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/search_settings`,
    querystring: {}
  }

  return await this.transport.request<GetSearchSettingsResponse>(params, transportOptions)
}

export interface PutSearchSettingsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  boosts?: {}
  search_fields?: {
    [k: string]: {
      weight?: number
    }
  }
}

export interface PutSearchSettingsResponse {}

/** Update search settings for the engine */
export async function putSearchSettings (this: That, opts: PutSearchSettingsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<PutSearchSettingsResponse>
export async function putSearchSettings (this: That, opts: PutSearchSettingsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<PutSearchSettingsResponse, unknown>>
export async function putSearchSettings (this: That, opts: PutSearchSettingsOptions, transportOptions?: TransportRequestOptions): Promise<PutSearchSettingsResponse>
export async function putSearchSettings (this: That, opts: PutSearchSettingsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'PUT',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/search_settings`,
    querystring: {},
    body: {}
  }

  if (opts.boosts !== undefined) (params.body as Record<string, any>).boosts = opts.boosts
  if (opts.search_fields !== undefined) (params.body as Record<string, any>).search_fields = opts.search_fields

  return await this.transport.request<PutSearchSettingsResponse>(params, transportOptions)
}
