/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface MultiSearchOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  queries: Array<{
    analytics?: {}
    boost?: {}
    facets?: {}
    filters?: {}
    group?: {}
    page?: {
      current?: number
      size?: number
    }
    query?: string
    result_fields?: {}
    search_fields?: {}
    sort?: {}
  }>
}

export interface MultiSearchResponse {}

/** Run several search in the same request */
export async function multiSearch (this: That, opts: MultiSearchOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<MultiSearchResponse>
export async function multiSearch (this: That, opts: MultiSearchOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<MultiSearchResponse, unknown>>
export async function multiSearch (this: That, opts: MultiSearchOptions, transportOptions?: TransportRequestOptions): Promise<MultiSearchResponse>
export async function multiSearch (this: That, opts: MultiSearchOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/multi_search`,
    querystring: {},
    body: {}
  }

  if (opts.queries !== undefined) (params.body as Record<string, any>).queries = opts.queries

  return await this.transport.request<MultiSearchResponse>(params, transportOptions)
}
