/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface ListSynonymSetsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  /**
   * The page to fetch. Defaults to 1
   */
  currentPage?: number
  /**
   * The number of results per page
   */
  pageSize?: number
}

export interface ListSynonymSetsResponse {}

/** Retrieve available synonym sets for the engine */
export async function listSynonymSets (this: That, opts: ListSynonymSetsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<ListSynonymSetsResponse>
export async function listSynonymSets (this: That, opts: ListSynonymSetsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<ListSynonymSetsResponse, unknown>>
export async function listSynonymSets (this: That, opts: ListSynonymSetsOptions, transportOptions?: TransportRequestOptions): Promise<ListSynonymSetsResponse>
export async function listSynonymSets (this: That, opts: ListSynonymSetsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'GET',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/synonyms`,
    querystring: {}
  }

  if (opts.currentPage !== undefined) (params.querystring as Record<string, any>).currentPage = opts.currentPage
  if (opts.pageSize !== undefined) (params.querystring as Record<string, any>).pageSize = opts.pageSize

  return await this.transport.request<ListSynonymSetsResponse>(params, transportOptions)
}

export interface CreateSynonymSetOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  synonyms: string[]
}

export interface CreateSynonymSetResponse {}

/** Create a new synonym set */
export async function createSynonymSet (this: That, opts: CreateSynonymSetOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<CreateSynonymSetResponse>
export async function createSynonymSet (this: That, opts: CreateSynonymSetOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<CreateSynonymSetResponse, unknown>>
export async function createSynonymSet (this: That, opts: CreateSynonymSetOptions, transportOptions?: TransportRequestOptions): Promise<CreateSynonymSetResponse>
export async function createSynonymSet (this: That, opts: CreateSynonymSetOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/synonyms`,
    querystring: {},
    body: {}
  }

  if (opts.synonyms !== undefined) (params.body as Record<string, any>).synonyms = opts.synonyms

  return await this.transport.request<CreateSynonymSetResponse>(params, transportOptions)
}
