/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface DeleteDocumentsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  documentIds: string[]
}

export interface DeleteDocumentsResponse {}

/** Delete documents by ID */
export async function deleteDocuments (this: That, opts: DeleteDocumentsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<DeleteDocumentsResponse>
export async function deleteDocuments (this: That, opts: DeleteDocumentsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<DeleteDocumentsResponse, unknown>>
export async function deleteDocuments (this: That, opts: DeleteDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<DeleteDocumentsResponse>
export async function deleteDocuments (this: That, opts: DeleteDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'DELETE',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/documents`,
    querystring: {},
    body: {}
  }

  params.body = opts?.documentIds
  return await this.transport.request<DeleteDocumentsResponse>(params, transportOptions)
}

export interface GetDocumentsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  documentIds: string[]
}

export interface GetDocumentsResponse {}

/** Retrieves one or more documents by ID */
export async function getDocuments (this: That, opts: GetDocumentsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<GetDocumentsResponse>
export async function getDocuments (this: That, opts: GetDocumentsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<GetDocumentsResponse, unknown>>
export async function getDocuments (this: That, opts: GetDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<GetDocumentsResponse>
export async function getDocuments (this: That, opts: GetDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'GET',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/documents`,
    querystring: {}
  }

  params.body = opts?.documentIds
  return await this.transport.request<GetDocumentsResponse>(params, transportOptions)
}

export interface PutDocumentsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  documents: Array<{
    id: string
    [k: string]: (string | number) | Array<string | number>
  }>
}

export interface PutDocumentsResponse {}

/** Partial update of documents */
export async function putDocuments (this: That, opts: PutDocumentsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<PutDocumentsResponse>
export async function putDocuments (this: That, opts: PutDocumentsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<PutDocumentsResponse, unknown>>
export async function putDocuments (this: That, opts: PutDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<PutDocumentsResponse>
export async function putDocuments (this: That, opts: PutDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'PATCH',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/documents`,
    querystring: {},
    body: {}
  }

  params.body = opts?.documents
  return await this.transport.request<PutDocumentsResponse>(params, transportOptions)
}

export interface IndexDocumentsOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  documents: Array<{
    id: string
    [k: string]: (string | number) | Array<string | number>
  }>
}

export interface IndexDocumentsResponse {}

/** Create or update documents */
export async function indexDocuments (this: That, opts: IndexDocumentsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<IndexDocumentsResponse>
export async function indexDocuments (this: That, opts: IndexDocumentsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<IndexDocumentsResponse, unknown>>
export async function indexDocuments (this: That, opts: IndexDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<IndexDocumentsResponse>
export async function indexDocuments (this: That, opts: IndexDocumentsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/documents`,
    querystring: {},
    body: {}
  }

  params.body = opts?.documents
  return await this.transport.request<IndexDocumentsResponse>(params, transportOptions)
}
