/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface SearchOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  [k: string]: unknown
}

export interface SearchResponse {
  [k: string]: unknown
}

/** Allows you to search over, facet and filter your data */
export async function search (this: That, opts: SearchOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<SearchResponse>
export async function search (this: That, opts: SearchOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<SearchResponse, unknown>>
export async function search (this: That, opts: SearchOptions, transportOptions?: TransportRequestOptions): Promise<SearchResponse>
export async function search (this: That, opts: SearchOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/search`,
    querystring: {},
    body: {}
  }

  return await this.transport.request<SearchResponse>(params, transportOptions)
}
