/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface AddUserPermissionsOptions {
  /**
   * Unique ID for a Custom API source, provided upon creation of a Custom API Source
   */
  content_source_id: string
  /**
   * The username in context
   */
  user: string
}

export interface AddUserPermissionsResponse {
  user: string
  /**
   * List of permissions
   */
  permissions: string[]
}

/** Adds one or more new permissions atop existing permissions */
export async function addUserPermissions (this: That, opts: AddUserPermissionsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<AddUserPermissionsResponse>
export async function addUserPermissions (this: That, opts: AddUserPermissionsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<AddUserPermissionsResponse, unknown>>
export async function addUserPermissions (this: That, opts: AddUserPermissionsOptions, transportOptions?: TransportRequestOptions): Promise<AddUserPermissionsResponse>
export async function addUserPermissions (this: That, opts: AddUserPermissionsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/ws/v1/sources/${encodeURIComponent(opts.content_source_id)}/permissions/${encodeURIComponent(opts.user)}/add`,
    querystring: {},
    body: {}
  }

  return await this.transport.request<AddUserPermissionsResponse>(params, transportOptions)
}
