/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface QuerySuggestionOptions {
  /**
   * Name of the engine
   */
  engine_name: string
  /**
   * A partial query for which to receive suggestions
   */
  query: string
  /**
   * List of fields to use to generate suggestions. Defaults to all text fields
   */
  fields?: string[]
  /**
   * Number of query suggestions to return. Must be between 1 and 20. Defaults to 5
   */
  size?: number
  [k: string]: unknown
}

export interface QuerySuggestionResponse {
  [k: string]: unknown
}

/** Provide relevant query suggestions for incomplete queries */
export async function querySuggestion (this: That, opts: QuerySuggestionOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<QuerySuggestionResponse>
export async function querySuggestion (this: That, opts: QuerySuggestionOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<QuerySuggestionResponse, unknown>>
export async function querySuggestion (this: That, opts: QuerySuggestionOptions, transportOptions?: TransportRequestOptions): Promise<QuerySuggestionResponse>
export async function querySuggestion (this: That, opts: QuerySuggestionOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'POST',
    path: `/api/as/v1/engines/${encodeURIComponent(opts.engine_name)}/query_suggestion`,
    querystring: {},
    body: {}
  }

  if (opts.query !== undefined) (params.querystring as Record<string, any>).query = opts.query
  if (opts.fields !== undefined) (params.querystring as Record<string, any>).fields = opts.fields
  if (opts.size !== undefined) (params.querystring as Record<string, any>).size = opts.size

  return await this.transport.request<QuerySuggestionResponse>(params, transportOptions)
}
