/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable import/export, @typescript-eslint/no-misused-new, @typescript-eslint/no-extraneous-class */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import { listEngines, createEngine } from './_api_as_v1_engines'
import { deleteEngine, getEngine } from './_api_as_v1_engines_engine_name'
import { getTopClicksAnalytics } from './_api_as_v1_engines_engine_name_analytics_clicks'
import { getCountAnalytics } from './_api_as_v1_engines_engine_name_analytics_counts'
import { getTopQueriesAnalytics } from './_api_as_v1_engines_engine_name_analytics_queries'
import { logClickthrough } from './_api_as_v1_engines_engine_name_click'
import { listCurations, createCuration } from './_api_as_v1_engines_engine_name_curations'
import { deleteCuration, getCuration, putCuration } from './_api_as_v1_engines_engine_name_curations_curation_id'
import { deleteDocuments, getDocuments, putDocuments, indexDocuments } from './_api_as_v1_engines_engine_name_documents'
import { listDocuments } from './_api_as_v1_engines_engine_name_documents_list'
import { getApiLogs } from './_api_as_v1_engines_engine_name_logs_api'
import { multiSearch } from './_api_as_v1_engines_engine_name_multi_search'
import { querySuggestion } from './_api_as_v1_engines_engine_name_query_suggestion'
import { getSchema, putSchema } from './_api_as_v1_engines_engine_name_schema'
import { search } from './_api_as_v1_engines_engine_name_search'
import { getSearchSettings, putSearchSettings } from './_api_as_v1_engines_engine_name_search_settings'
import { resetSearchSettings } from './_api_as_v1_engines_engine_name_search_settings_reset'
import { deleteMetaEngineSource, addMetaEngineSource } from './_api_as_v1_engines_engine_name_source_engines'
import { listSynonymSets, createSynonymSet } from './_api_as_v1_engines_engine_name_synonyms'
import { deleteSynonymSet, getSynonymSet, putSynonymSet } from './_api_as_v1_engines_engine_name_synonyms_synonym_set_id'

export default interface API {
  new(): API
  listEngines: typeof listEngines
  createEngine: typeof createEngine
  deleteEngine: typeof deleteEngine
  getEngine: typeof getEngine
  getTopClicksAnalytics: typeof getTopClicksAnalytics
  getCountAnalytics: typeof getCountAnalytics
  getTopQueriesAnalytics: typeof getTopQueriesAnalytics
  logClickthrough: typeof logClickthrough
  listCurations: typeof listCurations
  createCuration: typeof createCuration
  deleteCuration: typeof deleteCuration
  getCuration: typeof getCuration
  putCuration: typeof putCuration
  deleteDocuments: typeof deleteDocuments
  getDocuments: typeof getDocuments
  putDocuments: typeof putDocuments
  indexDocuments: typeof indexDocuments
  listDocuments: typeof listDocuments
  getApiLogs: typeof getApiLogs
  multiSearch: typeof multiSearch
  querySuggestion: typeof querySuggestion
  getSchema: typeof getSchema
  putSchema: typeof putSchema
  search: typeof search
  getSearchSettings: typeof getSearchSettings
  putSearchSettings: typeof putSearchSettings
  resetSearchSettings: typeof resetSearchSettings
  deleteMetaEngineSource: typeof deleteMetaEngineSource
  addMetaEngineSource: typeof addMetaEngineSource
  listSynonymSets: typeof listSynonymSets
  createSynonymSet: typeof createSynonymSet
  deleteSynonymSet: typeof deleteSynonymSet
  getSynonymSet: typeof getSynonymSet
  putSynonymSet: typeof putSynonymSet
}

export default class API {}
API.prototype.listEngines = listEngines
API.prototype.createEngine = createEngine
API.prototype.deleteEngine = deleteEngine
API.prototype.getEngine = getEngine
API.prototype.getTopClicksAnalytics = getTopClicksAnalytics
API.prototype.getCountAnalytics = getCountAnalytics
API.prototype.getTopQueriesAnalytics = getTopQueriesAnalytics
API.prototype.logClickthrough = logClickthrough
API.prototype.listCurations = listCurations
API.prototype.createCuration = createCuration
API.prototype.deleteCuration = deleteCuration
API.prototype.getCuration = getCuration
API.prototype.putCuration = putCuration
API.prototype.deleteDocuments = deleteDocuments
API.prototype.getDocuments = getDocuments
API.prototype.putDocuments = putDocuments
API.prototype.indexDocuments = indexDocuments
API.prototype.listDocuments = listDocuments
API.prototype.getApiLogs = getApiLogs
API.prototype.multiSearch = multiSearch
API.prototype.querySuggestion = querySuggestion
API.prototype.getSchema = getSchema
API.prototype.putSchema = putSchema
API.prototype.search = search
API.prototype.getSearchSettings = getSearchSettings
API.prototype.putSearchSettings = putSearchSettings
API.prototype.resetSearchSettings = resetSearchSettings
API.prototype.deleteMetaEngineSource = deleteMetaEngineSource
API.prototype.addMetaEngineSource = addMetaEngineSource
API.prototype.listSynonymSets = listSynonymSets
API.prototype.createSynonymSet = createSynonymSet
API.prototype.deleteSynonymSet = deleteSynonymSet
API.prototype.getSynonymSet = getSynonymSet
API.prototype.putSynonymSet = putSynonymSet
