/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import {
  Transport,
  TransportRequestParams,
  TransportRequestOptions,
  TransportRequestOptionsWithMeta,
  TransportRequestOptionsWithOutMeta,
  TransportResult
} from '@elastic/transport'
interface That { transport: Transport }

export interface ListPermissionsOptions {
  /**
   * Unique ID for a Custom API source, provided upon creation of a Custom API Source
   */
  content_source_id: string
  /**
   * Which page of results to request
   */
  currentPage?: number
  /**
   * The number of results to return in a page
   */
  pageSize?: number
}

export interface ListPermissionsResponse {
  meta: {
    page: {
      current: number
      total_pages: number
      total_results: number
      size: number
    }
  }
  results: Array<{
    user: string
    /**
     * List of permissions
     */
    permissions: string[]
  }>
}

/** Lists all permissions for all users */
export async function listPermissions (this: That, opts: ListPermissionsOptions, transportOptions?: TransportRequestOptionsWithOutMeta): Promise<ListPermissionsResponse>
export async function listPermissions (this: That, opts: ListPermissionsOptions, transportOptions?: TransportRequestOptionsWithMeta): Promise<TransportResult<ListPermissionsResponse, unknown>>
export async function listPermissions (this: That, opts: ListPermissionsOptions, transportOptions?: TransportRequestOptions): Promise<ListPermissionsResponse>
export async function listPermissions (this: That, opts: ListPermissionsOptions, transportOptions?: TransportRequestOptions): Promise<any> {
  const params: TransportRequestParams = {
    method: 'GET',
    path: `/api/ws/v1/sources/${encodeURIComponent(opts.content_source_id)}/permissions`,
    querystring: {}
  }

  if (opts.currentPage !== undefined) (params.querystring as Record<string, any>).currentPage = opts.currentPage
  if (opts.pageSize !== undefined) (params.querystring as Record<string, any>).pageSize = opts.pageSize

  return await this.transport.request<ListPermissionsResponse>(params, transportOptions)
}
