/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* eslint-disable import/export, @typescript-eslint/no-misused-new, @typescript-eslint/no-extraneous-class */

// This file was automatically generated by elastic/elastic-client-generator-js
// DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
// and elastic/elastic-client-generator-js to regenerate this file again.

import { indexDocuments } from './_api_ws_v1_sources_content_source_id_documents_bulk_create'
import { deleteDocuments } from './_api_ws_v1_sources_content_source_id_documents_bulk_destroy'
import { listExternalIdentities, createExternalIdentity } from './_api_ws_v1_sources_content_source_id_external_identities'
import { getExternalIdentity, putExternalIdentity, deleteExternalIdentity } from './_api_ws_v1_sources_content_source_id_external_identities_user'
import { listPermissions } from './_api_ws_v1_sources_content_source_id_permissions'
import { getUserPermissions, putUserPermissions } from './_api_ws_v1_sources_content_source_id_permissions_user'
import { addUserPermissions } from './_api_ws_v1_sources_content_source_id_permissions_user_add'
import { removeUserPermissions } from './_api_ws_v1_sources_content_source_id_permissions_user_remove'
import { createAnalyticsEvent } from './_api_ws_v1_analytics_event'
import { search } from './_api_ws_v1_search'

export default interface API {
  new(): API
  indexDocuments: typeof indexDocuments
  deleteDocuments: typeof deleteDocuments
  listExternalIdentities: typeof listExternalIdentities
  createExternalIdentity: typeof createExternalIdentity
  getExternalIdentity: typeof getExternalIdentity
  putExternalIdentity: typeof putExternalIdentity
  deleteExternalIdentity: typeof deleteExternalIdentity
  listPermissions: typeof listPermissions
  getUserPermissions: typeof getUserPermissions
  putUserPermissions: typeof putUserPermissions
  addUserPermissions: typeof addUserPermissions
  removeUserPermissions: typeof removeUserPermissions
  createAnalyticsEvent: typeof createAnalyticsEvent
  search: typeof search
}

export default class API {}
API.prototype.indexDocuments = indexDocuments
API.prototype.deleteDocuments = deleteDocuments
API.prototype.listExternalIdentities = listExternalIdentities
API.prototype.createExternalIdentity = createExternalIdentity
API.prototype.getExternalIdentity = getExternalIdentity
API.prototype.putExternalIdentity = putExternalIdentity
API.prototype.deleteExternalIdentity = deleteExternalIdentity
API.prototype.listPermissions = listPermissions
API.prototype.getUserPermissions = getUserPermissions
API.prototype.putUserPermissions = putUserPermissions
API.prototype.addUserPermissions = addUserPermissions
API.prototype.removeUserPermissions = removeUserPermissions
API.prototype.createAnalyticsEvent = createAnalyticsEvent
API.prototype.search = search
