name: Node CI

on:
  pull_request:
    paths:
      - 'packages/enterprise-search/**'
  push:
    paths:
      - 'packages/enterprise-search/**'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      working-directory: ./packages/enterprise-search
      run: |
        npm install

    - name: Lint
      working-directory: ./packages/enterprise-search
      run: |
        npm run lint

    - name: Unit test
      working-directory: ./packages/enterprise-search
      run: |
        npm run test

  license:
    name: License check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      working-directory: ./packages/enterprise-search
      run: |
        npm install

    - name: License checker
      working-directory: ./packages/enterprise-search
      run: |
        npm run license-checker
